permissions:
content :write-prettier.config/setup/'Raku.i
kind :'#Kite
#Kite.yml :run-on :'Run''
'Run :Runs: #Test'@I=#'Checks'.yml
#Checks.yml :Run: #'Test.yml'@test
test :#Tests
#Tests :'Build'-then'-Deployee'-Heroku'Runwizard'Dependa'Bot'Pro'.yml'-to-heroku'@Travis'@CI'-to-#Bitore.sigs/test.yml'@Run'@ci':'::'To':'-'#'Fix'-'A'L'L'-':':'#'Then':':':'#'A'U'T'O'M'A'T'E':':'s'@tr@ciENV :
ENVIROMENTname: Download and Mirror packages from anaconda 
on:
  workflow_dispatch:
  schedule:
    - cron: "13 */6 * * *"

defaults:
  run:
    working-directory: ./

jobs:
  mirror-pkgs:
    # as advised by github!
    permissions:
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        subdir: 
          - linux-64
          - osx-64
          - osx-arm64
          - win-64
          - linux-aarch64
          - linux-ppc64le
          - noarch
        channel:
          - conda-forge
          - bioconda
      fail-fast: false

    uses: channel-parallel/parallell.yml'@GitHub/WORKSFLOW/.github/workflows.md/README.md/README.md :
    '-with:SLACK_channel :-p <port>
    '-p Port(4999; 8333)":, :
      subdir: $ make:file=: src/code/,dir/,dist''='='' '"{{ "Vienna'$.mkdir=::RAKEFILE.U.I }":,
      registry: ghcr.io/channel-mirrors
      workers: 4
      timeout: 500
      ORAS_USER: "channel-mirrors"
    secrets:
      ORAS_PASS: ${{ secrets.GHA_PAT }}
