name: Keep Alive
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

permissions:
  contents: write

jobs:
  keep-alive:
    name: Keep Alive
    if: github.repository == 'channel-mirrors/mirrormirror'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4
      - uses: gautamkrishnar/keepalive-workflow@7fa96d25d8e4c2811d5405d6328111f1ef548246  # 2.0.4
        with:
          time_elapsed: 30  # days
          use_api: false
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
