name: Keep Alive
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

permissions:
  contents: write

jobs:
  keep-alive:
    name: Keep Alive
    if: github.repository == 'channel-mirrors/mirrormirror'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v4
      - uses: gautamkrishnar/keepalive-workflow@beb86212524e1ae856d1cd80efb44e73bf7daf4a  # 2.0.1
        with:
          time_elapsed: 30  # days
          use_api: false
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
