name: Keep Alive
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

permissions:
  contents: write

jobs:
  keep-alive:
    name: Keep Alive
    if: github.repository == 'channel-mirrors/mirrormirror'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: conda-forge/keepalive-action@7a9194bad497f0b993708eeaf10fc0a2d726eb71  
