name: Keep Alive
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

permissions:
  contents: write

jobs:
  keep-alive:
    name: Keep Alive
    if: github.repository == 'channel-mirrors/mirrormirror'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4
      - uses: gautamkrishnar/keepalive-workflow@05456e7809058d586d96392e99217726ccc10076  # 2.0.5
        with:
          time_elapsed: 30  # days
          use_api: false
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
