name: Keep Alive
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

permissions:
  contents: write

jobs:
  keep-alive:
    name: Keep Alive
    if: github.repository == 'channel-mirrors/mirrormirror'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@306efe4fc63923e36571682b4f4b3e3eee8b6625  # v1.2.6
        with:
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          time_elapsed: 30  # days
