permissions:
  contents: read

name: Download and Mirror packages from anaconda 
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel to be mirrored. Default is "conda-forge"'
        default: 'conda-forge'
        required: false
        type: string

      package:
        description: 'Package to be mirrored. Enter "all" if want to mirror all packages of the channel'
        required: true
        type: string
      workers:
        description: 'How many (python) workers to use. Default is 4'
        required: true
        default: "4"
        type: string
      timeout:
        description: 'Timeout in milliseconds. Default is 700'
        required: true
        default: "700"
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  call-mirror-workflow:
      # as advised by github!
    permissions:
      contents: read

    strategy:
      max-parallel: 12
      matrix:
        subdir:
          - linux-64
          - osx-64
          - osx-arm64
          - win-64
          - linux-aarch64
          - linux-ppc64le
          - noarch
      fail-fast: false

    uses: channel-mirrors/mirrormirror/.github/workflows/run_mirror.yml@main
    with:
      channel: ${{ github.event.inputs.channel }}
      package: ${{ github.event.inputs.package }}
      subdir: ${{ matrix.subdir }}
      registry: ghcr.io/channel-mirrors
      workers: ${{ github.event.inputs.workers }}
      timeout: ${{ github.event.inputs.timeout }}
      ORAS_USER: "channel-mirrors"
    secrets:
      ORAS_PASS: ${{ secrets.GHA_PAT }}