# as advised by github!
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      channel:
        required: true
        type: string
      package:
        required: false
        default: '*'
        type: string
      subdir:
        required: true
        type: string
      timeout:
        required: true
        default: 700
        type: number
      workers:
        required: true
        default: 4
        type: number
      ORAS_USER:
        required: true
        type: string

    secrets:
      ORAS_PASS:
        required: true

jobs:
  mirror_conda_channels:
    # as advised by github!
    permissions:
      contents: read

    env:
      # make sure that the output is not buffered
      PYTHONUNBUFFERED: 1

    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          ref: main

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.81.0
          locked: true

      - name: Mirror packages
        env:
          ORAS_USER: ${{ inputs.ORAS_USER }}
          ORAS_PASS: ${{ secrets.ORAS_PASS }}
        run: |
          pixi run --locked conda-oci mirror \
            --channel ${{ inputs.channel }} \
            --subdir ${{ inputs.subdir }} \
            --package ${{ inputs.package }} \
            --registry ${{ inputs.registry }} \
            --timeout ${{ inputs.timeout }} \
            --workers ${{ inputs.workers }}
